Лабораторная 3
NeKitos/-PY1 pull request #1
Opened 2022-10-16 16:01 UTC by NeKitos

С task8 Мучился долго, не совпадал ответ, возможен не один ответ, могу пересчитать, но через эксель у меня тоже получилось 6 месяцев.
С уважением, Орлов Н.И.

2022-10-16 17:44 UTC, meat9 requested changes

2022-10-16 17:44 UTC, meat9 commented on лабораторная 3/task8.py
> +while ostatok >= 0:
Условие не верное. Вам нужно сравнивать не с 0. и как результат не корректный ответ.
В самом цикле все в порядке.


Еще у вас в СДО статус решения "Черновик", он должен быть в статусе ожидает проверки. Прошу это тоже исправить

2022-10-17 17:14 UTC, NeKitos commented on лабораторная 3/task8.py
> +while ostatok >= 0:
Исправил task8 через edit file. Не знаю, правильно ли работаю в github, не особо разобрался)

2022-10-17 19:56 UTC, meat9 requested changes

2022-10-17 19:56 UTC, meat9 commented on лабораторная 3/task8.py
> +while money_capital >= (spend + (spend * ((month + 1) * increase))):
Перебор в условии. Нужно сделать проще

2022-10-18 15:00 UTC, NeKitos commented on лабораторная 3/task8.py
> +while money_capital >= (spend + (spend * ((month + 1) * increase))):
Исправил

2022-10-18 19:36 UTC, meat9 approved these changes

2022-10-18 19:36 UTC, meat9 commented on лабораторная 3/task8.py
> +loss = salary - (spend + (spend * (month * increase)))
Это наверное лишнее

2022-10-18 19:36 UTC, meat9 commented on лабораторная 3/task8.py
> +while money_capital >= (spend + (1 + increase)):
Достаточно было вот этого
money_capital >= spend

2022-10-18 19:36 UTC, meat9 commented on лабораторная 3/task8.py
> +    loss = salary - (spend + (spend * (month * increase)))
Сложное решение. Чем меньше скобок в формулах - тем лучше

2022-11-01 15:37 UTC, merged